services:
  host:
    build:
      context: .
      dockerfile: Server/Api/Dockerfile
    environment:
      - ConnectionStrings__DbConnection=Server=db;Database=ServerDb;User Id=sa;Password=S0MEstrongPA55w0rd;Encrypt=False;
      - ConnectionStrings__CacheConnection=cache:6379
    restart: always
    depends_on:
      - db
      - cache
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=S0MEstrongPA55w0rd
    volumes:
      - db:/var/opt/mssql
    restart: always
  cache:
    image: redis:7.4-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    restart: always
volumes:
  host:
  cache:
  db: